"""Field evidence and the closure gate.

Mirrors the second half of migrations/sql/0005_defects_evidence.sql.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal
from typing import Any

from geoalchemy2 import Geography
from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    Text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base, pg_enum


class Evidence(Base):
    """One captured record.

    `id` is generated by the client, offline, at capture time and is never
    reassigned — that is what makes POST /evidence/sync an idempotent upsert
    instead of a duplicate-row generator on a flaky link.

    `verdict` is the intrinsic trustworthiness of the capture (device
    integrity, mock location, clock consistency, chain continuity), computed
    once at sync and never mutated. Whether this evidence is *fit to close a
    specific target* is a separate judgment, recorded per attempt.
    """

    __tablename__ = "evidence"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    tenant_id: Mapped[str] = mapped_column(Text, ForeignKey("tenant.id"))
    mine_id: Mapped[str] = mapped_column(Text, ForeignKey("mine.id"))
    captured_by_person_id: Mapped[str] = mapped_column(Text, ForeignKey("person.id"))
    capture_appointment_id: Mapped[str | None] = mapped_column(Text, ForeignKey("appointment.id"))
    for_instance_id: Mapped[str | None] = mapped_column(Text, ForeignKey("obligation_instance.id"))
    for_capa_id: Mapped[str | None] = mapped_column(Text, ForeignKey("capa.id"))
    for_defect_id: Mapped[str | None] = mapped_column(Text, ForeignKey("defect.id"))
    for_observation_id: Mapped[str | None] = mapped_column(Text, ForeignKey("observation.id"))
    capture_path: Mapped[str] = mapped_column(pg_enum("capture_path"))
    media_type: Mapped[str] = mapped_column(pg_enum("evidence_media_type"))
    content_hash: Mapped[str] = mapped_column(Text)
    storage_bucket: Mapped[str] = mapped_column(Text)
    storage_key: Mapped[str] = mapped_column(Text)
    byte_size: Mapped[int] = mapped_column(BigInteger)
    content_type: Mapped[str] = mapped_column(Text)
    client_schema_version: Mapped[int] = mapped_column(Integer)
    device_id: Mapped[str] = mapped_column(Text)
    chain_sequence: Mapped[int] = mapped_column(Integer)
    prev_hash: Mapped[str | None] = mapped_column(Text)
    device_integrity_verdict: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    location: Mapped[Any | None] = mapped_column(Geography("POINT", srid=4326))
    location_accuracy_m: Mapped[Decimal | None] = mapped_column(Numeric(8, 2))
    location_provider: Mapped[str | None] = mapped_column(Text)
    satellites_used: Mapped[int | None] = mapped_column(Integer)
    constellations: Mapped[list[str] | None] = mapped_column(ARRAY(Text))
    is_mock_location: Mapped[bool] = mapped_column(Boolean)
    captured_at_wall: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    captured_at_monotonic_ns: Mapped[int | None] = mapped_column(BigInteger)
    verified_window_start: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    verified_window_end: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    server_received_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    verdict: Mapped[str] = mapped_column(pg_enum("evidence_verdict"))
    verdict_reasons: Mapped[list[Any]] = mapped_column(JSONB)
    at_subunit_id: Mapped[str | None] = mapped_column(Text, ForeignKey("subunit.id"))
    at_asset_id: Mapped[str | None] = mapped_column(Text, ForeignKey("asset.id"))
    synced_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    sync_error: Mapped[str | None] = mapped_column(Text)
    row_version: Mapped[int] = mapped_column(Integer)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))


class EvidenceVerificationAttempt(Base):
    """Every closure attempt, accepted or blocked, leaves one row.

    This is what makes "closure blocked, here is why" a permanent queryable
    fact rather than a live-only computation that cannot be reproduced if the
    decision is challenged later.
    """

    __tablename__ = "evidence_verification_attempt"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    tenant_id: Mapped[str] = mapped_column(Text, ForeignKey("tenant.id"))
    capa_id: Mapped[str | None] = mapped_column(Text, ForeignKey("capa.id"))
    obligation_instance_id: Mapped[str | None] = mapped_column(
        Text, ForeignKey("obligation_instance.id")
    )
    evidence_id: Mapped[str] = mapped_column(Text, ForeignKey("evidence.id"))
    attempted_by_person_id: Mapped[str] = mapped_column(Text, ForeignKey("person.id"))
    attempted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    spatial_evaluation_id: Mapped[str | None] = mapped_column(Text)
    distance_m: Mapped[Decimal | None] = mapped_column(Numeric(10, 2))
    geofence_radius_m: Mapped[Decimal | None] = mapped_column(Numeric(10, 2))
    within_geofence: Mapped[bool | None] = mapped_column(Boolean)
    outcome: Mapped[str] = mapped_column(pg_enum("verification_outcome"))
    reason_detail: Mapped[dict[str, Any] | None] = mapped_column(JSONB)
    override_by_person_id: Mapped[str | None] = mapped_column(Text, ForeignKey("person.id"))
    override_appointment_id: Mapped[str | None] = mapped_column(Text, ForeignKey("appointment.id"))
    override_reason: Mapped[str | None] = mapped_column(Text)


__all__ = ["Evidence", "EvidenceVerificationAttempt"]
